// Code generated by Slice Machine. DO NOT EDIT.

			import dynamic from 'next/dynamic'

			export const components = {
				call_to_action: dynamic(() => import('./CallToAction')),
collection: dynamic(() => import('./Collection')),
content: dynamic(() => import('./Content')),
feed: dynamic(() => import('./Feed')),
form_intake: dynamic(() => import('./FormIntake')),
hero: dynamic(() => import('./Hero')),
interactive: dynamic(() => import('./Interactive'))
			}