// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
	hero: dynamic(() => import('./Hero')),
	content: dynamic(() => import('./Content')),
	collection: dynamic(() => import('./Collection')),
	call_to_action: dynamic(() => import('./CallToAction')),
	feed: dynamic(() => import('./Feed')),
	form_intake: dynamic(() => import('./FormIntake')),
}
