import _BLUR from '@/img/blur.jpg'
import _COVER from '@/img/cover.jpg'
import _IMAGE from '@/img/fallback.jpg'

//// Assets
//
export const FALLBACK_IMAGE = _IMAGE
export const FALLBACK_BLUR = _BLUR
export const FALLBACK_BLUR_DATA =
	'/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAYGBgYGBgYHBwYJCgkKCQ0MCwsMDRQODw4PDhQfExYTExYTHxshGxkbIRsxJiIiJjE4Ly0vOEQ9PURWUVZwcJYBBgYGBgYGBgcHBgkKCQoJDQwLCwwNFA4PDg8OFB8TFhMTFhMfGyEbGRshGzEmIiImMTgvLS84RD09RFZRVnBwlv/CABEIAAwADAMBIgACEQEDEQH/xAAWAAEBAQAAAAAAAAAAAAAAAAAGBwj/2gAIAQEAAAAAW1PHzT//xAAUAQEAAAAAAAAAAAAAAAAAAAAB/9oACAECEAAAAD//xAAUAQEAAAAAAAAAAAAAAAAAAAAC/9oACAEDEAAAAD//xAAhEAACAgEEAwEBAAAAAAAAAAABAgMEEQAFEyEGEkEigf/aAAgBAQABPwBd6nhmuV2FcyQyVvWRkKxujx/vjP1gw1t1qnZo1Z22/jaSNWZHCBgSPuTqvdtmbj53Csk3Q6C+kZxgfzB0PJvIe8bvYUDrAI+a/8QAGREBAAIDAAAAAAAAAAAAAAAAAQACERIU/9oACAECAQE/AOVqpsYCf//EABgRAQEAAwAAAAAAAAAAAAAAAAECABMh/9oACAEDAQE/ANwyMz1c/9k='

export const _BLUR64 = `data:image/jpeg;base64,${FALLBACK_BLUR_DATA}`

//// Brand
//
export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL
export const SITE_NAME = process.env.NEXT_PUBLIC_SITE_NAME
export const SITE_TITLE = ''
export const SITE_DESCRIPTION = ''
export const PATIENT_PORTAL_URL =
	'https://www.mymedicallocker.com/mml/login.html'
