//// Contact
//
export const LOCATIONS = [
	{
		href: '/location/nine-mile-crossing',
		text: 'Nine Mile Crossing',
	},
	{ href: '/location/palafox', text: 'Palafox' },
	{ href: '/location/fairfield', text: 'Fairfield' },
	{
		href: '/location/baptist-hospital',
		text: 'Baptist Hospital',
	},
	{ href: '/location/milton', text: 'Milton' },
	{ href: '/location/foley', text: 'Foley' },
	{ href: '/location/fairhope', text: 'Fairhope' },
	{ href: '/location/navarre', text: 'Navarre' },
]

export const BRANDS = {
	Adensco: ['Fairfield'],
	Adidas: ['Milton'],
	Adria: ['Fairfield'],
	'Ann Taylor': ['Foley'],
	'Anne Klein': [
		'Foley',
		'Nine Mile Crossing',
		'Fairhope',
		'Milton',
		'Navarre',
	],
	Aristar: ['Fairfield', 'Palafox', 'Fairhope', 'Baptist Hospital'],
	'Armani Exchange': ['Fairfield'],
	'Autoflex/Flexon': ['Fairfield'],
	Bajio: ['Baptist Hospital'],
	'Bajio Sunglasses': ['Palafox'],
	'BCBG Max Azria': ['Palafox', 'Milton'],
	BCBGMAXAZRIA: ['Foley', 'Nine Mile Crossing'],
	Bebe: ['Fairhope'],
	BEBE: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Betsey Johnson': [
		'Foley',
		'Palafox',
		'Fairhope',
		'Milton',
		'Navarre',
	],
	'Big Mens Eyewear Club': ['Navarre'],
	Bontaniq: ['Baptist Hospital'],
	Boss: ['Foley', 'Palafox'],
	'Brooks Brothers': ['Palafox', 'Navarre'],
	Burberry: ['Palafox'],
	Callaway: ['Navarre'],
	'Calvin Klein': ['Fairhope', 'Milton', 'Navarre'],
	'Calvin Klein Jeans': ['Foley', 'Nine Mile Crossing'],
	Cargo: ['Fairhope'],
	'Carolina Herrara': ['Baptist Hospital'],
	'Carolina Herrera': ['Palafox'],
	'Carolina Herrerra': ['Palafox'],
	Carrera: [
		'Foley',
		'Fairfield',
		'Palafox',
		'Fairhope',
		'Baptist Hospital',
		'Navarre',
	],
	Cazal: ['Palafox'],
	Champion: ['Foley', 'Milton'],
	Charmant: ['Nine Mile Crossing', 'Palafox'],
	Chloe: ['Palafox'],
	Coach: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Cole Haan': [
		'Foley',
		'Nine Mile Crossing',
		'Fairhope',
		'Baptist Hospital',
		'Navarre',
	],
	Columbia: [
		'Fairfield',
		'Nine Mile Crossing',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Cool Clip': ['Foley', 'Palafox', 'Fairhope', 'Milton'],
	Cosmopolitan: ['Palafox'],
	Costa: [
		'Foley',
		'Nine Mile Crossing',
		'Palafox',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Costa Del Mar': ['Fairhope'],
	'Danny Gokey': ['Foley', 'Palafox'],
	'David Beckham': ['Palafox'],
	'Demi & Dash': [
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Dilli dalli': ['Nine Mile Crossing'],
	'Dilli Dalli': [
		'Foley',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	Diva: ['Palafox'],
	Divaldi: ['Palafox'],
	DKNY: ['Nine Mile Crossing'],
	'Dolce & Gabanna': ['Baptist Hospital'],
	'Dolce & Gabbana': ['Palafox'],
	Dragon: ['Foley', 'Palafox', 'Navarre'],
	'Draper James': [
		'Foley',
		'Fairfield',
		'Fairhope',
		'Baptist Hospital',
		'Navarre',
	],
	'Ducks Unlimited': ['Foley', 'Palafox', 'Milton'],
	'Eddie Bauer': ['Fairfield'],
	Elle: ['Palafox'],
	'Ellen Tracy': ['Fairhope', 'Milton'],
	'Emporio Armani': ['Navarre'],
	'Ernest Hemingway': ['Milton', 'Navarre'],
	Esquire: ['Fairfield', 'Baptist Hospital', 'Navarre'],
	Etnia: ['Palafox'],
	Fendi: ['Foley', 'Palafox'],
	Flexon: [
		'Nine Mile Crossing',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	FYSH: ['Foley'],
	GAP: ['Nine Mile Crossing'],
	Genesis: ['Navarre'],
	'Genevieve Boutique Plus': ['Navarre'],
	Givenchy: ['Palafox'],
	Gucci: ['Foley', 'Nine Mile Crossing', 'Palafox'],
	Guess: ['Fairfield', 'Milton'],
	'GX by Gwen Stefani': ['Palafox'],
	'Harley Davidson': ['Palafox', 'Milton'],
	'Hello Kitty': ['Navarre'],
	Illa: ['Fairfield'],
	ILLA: [
		'Palafox',
		'Palafox',
		'Fairhope',
		'Baptist Hospital',
		'Navarre',
	],
	'Isaac Mizrahi': ['Palafox'],
	'Issac Mizrahi': ['Fairfield'],
	Izod: ['Fairhope', 'Baptist Hospital'],
	IZOD: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Navarre',
	],
	'Jessica McClintock': ['Fairhope', 'Baptist Hospital', 'Navarre'],
	'Jill Stuart': ['Milton'],
	'Jimmy Crystal': ['Foley', 'Palafox'],
	'Joan Collins': [
		'Fairfield',
		'Nine Mile Crossing',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Joseph Abboud': [
		'Foley',
		'Nine Mile Crossing',
		'Fairhope',
		'Navarre',
	],
	'Juicy couture': ['Fairfield'],
	'Karl Lagerfeld': ['Foley', 'Baptist Hospital', 'Navarre'],
	'Kate Spade': [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Fairhope',
		'Baptist Hospital',
		'Navarre',
	],
	Kensie: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Baptist Hospital',
	],
	'L.A.M.B.': ['Foley', 'Fairfield', 'Palafox', 'Baptist Hospital'],
	Lacoste: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Laugh Out Loud': ['Fairhope'],
	'Lenton & Rusby': ['Fairhope', 'Milton', 'Navarre'],
	'Lenton and Rusby': ['Foley', 'Fairfield', 'Baptist Hospital'],
	'Life is Good': ['Foley'],
	'Life Is Good': ['Palafox', 'Milton'],
	'Lilly Pulitzer': [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
	],
	'London Fog': ['Milton'],
	Longchamp: [
		'Foley',
		'Nine Mile Crossing',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Lulu Guiness': ['Foley', 'Palafox'],
	'Marc Jacobs': ['Foley'],
	'Marchon NYC': ['Fairhope', 'Navarre'],
	MarchonNYC: ['Baptist Hospital'],
	'Maui Jim': ['Foley', 'Palafox', 'Fairhope'],
	'Max and Co': ['Fairfield'],
	MaxMara: ['Nine Mile Crossing'],
	'Michael Kors': [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	Morel: ['Palafox'],
	'My Little Pony': ['Navarre'],
	Nautica: [
		'Foley',
		'Nine Mile Crossing',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'New Balance': ['Navarre'],
	Nike: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Nine west': ['Fairfield'],
	'Nine West': ['Fairhope'],
	Oakley: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Fairhope',
		'Baptist Hospital',
		'Navarre',
	],
	'Ocean Pacific': ['Baptist Hospital', 'Navarre'],
	'Oliver Peoples': ['Palafox'],
	'OP- Ocean Pacific': ['Fairhope'],
	Paradigm: ['Foley', 'Nine Mile Crossing', 'Milton', 'Navarre'],
	Paradox: ['Palafox'],
	'Paw Patrol': ['Navarre'],
	Penguin: ['Foley', 'Baptist Hospital'],
	'Perry Ellis': ['Milton'],
	Polaroid: ['Fairfield', 'Milton', 'Baptist Hospital'],
	Polo: ['Baptist Hospital'],
	'Polo Ralph Lauren': [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Fairhope',
		'Milton',
		'Navarre',
	],
	Prada: ['Palafox'],
	'Randy Jackson': ['Palafox'],
	'Ray Ban': ['Fairhope', 'Baptist Hospital', 'Navarre'],
	Rayban: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Milton',
	],
	'Real Tree': ['Navarre'],
	'Saint Laurent': ['Foley', 'Nine Mile Crossing', 'Palafox'],
	"Shaquille O'neal": ['Nine Mile Crossing'],
	"Shaquille O'Neal": ['Palafox'],
	Silhouette: [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Fairhope',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	Stetson: ['Palafox'],
	'Steve Madden': [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Palafox',
		'Milton',
		'Baptist Hospital',
		'Navarre',
	],
	'Stuart Weitzman': ['Palafox'],
	Superflex: ['Foley', 'Fairfield', 'Milton'],
	Swarovski: ['Palafox'],
	Takumi: ['Foley'],
	'Ted Baker': ['Foley', 'Palafox'],
	'The Original Penguin': ['Navarre'],
	'Tiffany & Company': ['Palafox', 'Fairhope'],
	'Titan Flex': ['Palafox'],
	'Tom Ford': ['Palafox'],
	'Tommy Hilfiger': [
		'Foley',
		'Fairfield',
		'Nine Mile Crossing',
		'Navarre',
	],
	'Tory Burch': ['Palafox', 'Palafox', 'Fairhope', 'Navarre'],
	Transformers: ['Navarre'],
	'Treis Jolie': ['Navarre'],
	'Trina Turk': ['Palafox'],
	'Under Armour': [
		'Foley',
		'Fairfield',
		'Fairhope',
		'Milton',
		'Navarre',
	],
	'Under Armour ': ['Baptist Hospital'],
	'Valerie Spencer': ['Fairfield', 'Milton', 'Milton', 'Navarre'],
	'Vera Bradley': ['Foley', 'Palafox', 'Milton'],
	'Vera Wang': ['Foley', 'Navarre'],
	Versace: [
		'Nine Mile Crossing',
		'Palafox',
		'Fairhope',
		'Baptist Hospital',
	],
	Vogue: ['Navarre'],
	'Wiley X': ['Foley', 'Palafox', 'Milton', 'Navarre'],
	XOXO: ['Foley', 'Palafox'],
	'Zac Posen': ['Foley'],
}
